language: cpp

before_install:
  # Qt repository   
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  # g++ repository
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  # Qt install
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  # g++ install
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - qmake
  - make --file Makefile -j2
