.TH "Arbre" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arbre \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCellule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetState\fP (int x)"
.br
.ti -1c
.RI "\fBArbre\fP (int col, int row, const \fBEssence\fP *const _essence, unsigned int _age=0, unsigned int _humidite=20, int _coefficient=1)"
.br
.ti -1c
.RI "\fBArbre\fP (\fBCellule\fP *cell, int col, int row, const \fBEssence\fP *const _essence, unsigned int age=0, unsigned int _humidite=20, int _coefficient=1)"
.br
.ti -1c
.RI "\fBArbre\fP (int col, int row, \fBCellule\fP *cell, const \fBEssence\fP *const _essence, unsigned int _humidite, int _hp, int _coefficient=1)"
.br
.ti -1c
.RI "void \fBinitialise\fP (unsigned age)"
.br
.ti -1c
.RI "virtual int \fBgetState\fP () const "
.br
.ti -1c
.RI "int \fBgetPv\fP () const "
.br
.ti -1c
.RI "float \fBgetCoeff\fP () const "
.br
.ti -1c
.RI "float \fBgetHumidity\fP () const "
.br
.ti -1c
.RI "const \fBCoordonnee\fP & \fBgetPos\fP () const "
.br
.ti -1c
.RI "const \fBEssence\fP * \fBgetEssence\fP () const "
.br
.ti -1c
.RI "void \fBsetCoefficient\fP (float x)"
.br
.ti -1c
.RI "void \fBspark\fP (float coefTransmission=1\&.0)"
.br
.ti -1c
.RI "bool \fBburn\fP (float coefBrulure=1\&.0)"
.br
.ti -1c
.RI "virtual bool \fBisOnFire\fP () const "
.br
.ti -1c
.RI "void \fBdelay\fP (float coefRalentissement)"
.br
.ti -1c
.RI "void \fBkindle\fP ()"
.br
.ti -1c
.RI "void \fBblast\fP ()"
.br
.ti -1c
.RI "void \fBuproot\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Arbre::Arbre (int col, int row, const \fBEssence\fP *const _essence, unsigned int _age = \fC0\fP, unsigned int _humidite = \fC20\fP, int _coefficient = \fC1\fP)"
Construit un arbre non enflammé à partir d'une position 
.PP
\fBParameters:\fP
.RS 4
\fIage\fP age de l'arbre, permet de calculer ses PV 
.br
\fIall\fP paramètres d'initialisation des attributs de l'arbre 
.RE
.PP

.SS "Arbre::Arbre (\fBCellule\fP * cell, int col, int row, const \fBEssence\fP *const _essence, unsigned int age = \fC0\fP, unsigned int _humidite = \fC20\fP, int _coefficient = \fC1\fP)"
Construit un arbre non enflammé 'à partir' d'une cellule 
.PP
\fBParameters:\fP
.RS 4
\fIcell\fP cellule à remplacer, elle est désallouée 
.br
\fIage\fP age de l'arbre, permet de calculer ses PV 
.br
\fIall\fP paramètres d'initialisation des attributs de l'arbre 
.RE
.PP

.SS "Arbre::Arbre (int col, int row, \fBCellule\fP * cell, const \fBEssence\fP *const _essence, unsigned int _humidite, int _hp, int _coefficient = \fC1\fP)"
Construit un arbre non enflammé par dessus une cellule, en donnant des PV plutot que de les calculer avec l'age 
.PP
\fBParameters:\fP
.RS 4
\fIcell\fP cellule à remplacer, elle est désallouée 
.br
\fIall\fP paramètres d'initialisation des attributs de l'arbre 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool Arbre::burn (float coefBrulure = \fC1\&.0\fP)"
Retire un nombre de points de vie à l'arbre 
.PP
\fBAuthor:\fP
.RS 4
Florian 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcoef\fP 
.RE
.PP

.SS "void Arbre::delay (float coefRalentissement)"
Modifie la vitesse de transmisson du feu (multiplié) 
.PP
\fBAuthor:\fP
.RS 4
Ugo 
.RE
.PP

.SS "void Arbre::initialise (unsigned age)"
Initialise les points de vie de l'arbre en fonction des caractères de son essence et de ses propriétés discrètes 
.PP
\fBAuthor:\fP
.RS 4
Ugo Florian 
.RE
.PP

.SS "void Arbre::spark (float coefTransmission = \fC1\&.0\fP)"
L'arbre reçoit des flammes d'un voisin et risque de s'enflammer 
.PP
\fBAuthor:\fP
.RS 4
Florian 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcoefTransmission\fP force de transmisson de l'arbre en feu au voisin, correspond à un rapport (force du vent)/(dist à l'arbre en feu) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
