.TH "CelluleVide" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CelluleVide \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCellule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetState\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
