.TH "Cellule" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cellule \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBArbre\fP, and \fBCelluleVide\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBgetState\fP () const  =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
