.TH "cpplint._PreprocessorInfo" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpplint._PreprocessorInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, stack_before_if)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstack_before_if\fP"
.br
.ti -1c
.RI "\fBstack_before_else\fP"
.br
.ti -1c
.RI "\fBseen_else\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Stores checkpoints of nesting stacks when #if/#else is seen.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
