.TH "cpplint._IncludeError" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpplint._IncludeError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Indicates a problem with the include order in a file.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
