.TH "cpplint._ClassInfo" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpplint._ClassInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcpplint\&._BlockInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, name, class_or_struct, clean_lines, linenum)"
.br
.ti -1c
.RI "def \fBCheckBegin\fP (self, filename, clean_lines, linenum, error)"
.br
.ti -1c
.RI "def \fBCheckEnd\fP (self, filename, clean_lines, linenum, error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBname\fP"
.br
.ti -1c
.RI "\fBstarting_linenum\fP"
.br
.ti -1c
.RI "\fBis_derived\fP"
.br
.ti -1c
.RI "\fBcheck_namespace_indentation\fP"
.br
.ti -1c
.RI "\fBaccess\fP"
.br
.ti -1c
.RI "\fBis_struct\fP"
.br
.ti -1c
.RI "\fBclass_indent\fP"
.br
.ti -1c
.RI "\fBlast_line\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Stores information about a class.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
