.TH "deprecated" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBFireWidget::actionReceived\fP (int x)\fP" 1c
.IP "\fBMember \fBFireWidget::drawTree\fP (const \fBArbre\fP *ab)\fP" 1c
.IP "\fBMember \fBFireWidget::mousePressEvent\fP (QMouseEvent *event)\fP" 1c
.IP "\fBMember \fBForet::loadSizes\fP (std::ifstream *file)\fP" 1c
taille lues dans fwelcome, pour initialiser les tailles des fenetres  
.IP "\fBMember \fBForet::setValues\fP (int largeur, int hauteur, float coef)\fP" 1c
.IP "\fBMember \fBForet::spark\fP (int col, int row, int intensite)\fP" 1c
.IP "\fBMember \fBForet::transition\fP (\fBArbre\fP *ab)\fP" 1c
transmission sans vent  
.IP "\fBMember \fBTiXmlHandle::Element\fP () const \fP" 1c
use ToElement\&. Return the handle as a \fBTiXmlElement\fP\&. This may return null\&.  
.IP "\fBMember \fBTiXmlHandle::Node\fP () const \fP" 1c
use ToNode\&. Return the handle as a \fBTiXmlNode\fP\&. This may return null\&.  
.IP "\fBMember \fBTiXmlHandle::Text\fP () const \fP" 1c
use \fBToText()\fP Return the handle as a \fBTiXmlText\fP\&. This may return null\&.  
.IP "\fBMember \fBTiXmlHandle::Unknown\fP () const \fP" 1c
use \fBToUnknown()\fP Return the handle as a \fBTiXmlUnknown\fP\&. This may return null\&. 
.PP

