.TH "Essence" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Essence \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEssence\fP (unsigned int i, std::string nom, int masse, float _diametre, float _hauteur, unsigned int age, bool t)"
.br
.ti -1c
.RI "\fBEssence\fP (const \fBEssence\fP &other)"
.br
.ti -1c
.RI "unsigned \fBgetIndice\fP () const "
.br
.ti -1c
.RI "std::string \fBgetName\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetMasse\fP () const "
.br
.ti -1c
.RI "float \fBgetDiametre\fP () const "
.br
.ti -1c
.RI "float \fBgetHauteur\fP () const "
.br
.ti -1c
.RI "unsigned \fBgetAgeMaturite\fP () const "
.br
.ti -1c
.RI "bool \fBgetType\fP () const "
.br
.ti -1c
.RI "void \fBsetName\fP (std::string x)"
.br
.ti -1c
.RI "void \fBsetMasse\fP (int x)"
.br
.ti -1c
.RI "void \fBsetType\fP (bool t)"
.br
.ti -1c
.RI "void \fBsetHauteur\fP (float h)"
.br
.ti -1c
.RI "void \fBsetDiametre\fP (float d)"
.br
.ti -1c
.RI "virtual \fBEssence\fP & \fBoperator=\fP (const \fBEssence\fP &other)"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
