.TH "qt_meta_stringdata_FireScreen_t" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_FireScreen_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [16]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [150]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
