.TH "Terminal" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terminal \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminal\fP (int hauteur, int largeur, float proba, long int nTemps=0\&.60, float coef_brulure=1\&.0, bool t=0)"
.br
.ti -1c
.RI "void \fBend\fP ()"
.br
.ti -1c
.RI "void \fBafficheContour\fP (int largeur)"
.br
.ti -1c
.RI "void \fBafficheCase\fP (const \fBCellule\fP *cell)"
.br
.ti -1c
.RI "void \fBafficheLigne\fP (int num_ligne)"
.br
.ti -1c
.RI "void \fBafficheForet\fP ()"
.br
.ti -1c
.RI "void \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "int \fBmain_terminal\fP (int argc, char **argv)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
