.TH "TiXmlOutStream" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TiXmlOutStream \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTiXmlString\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTiXmlOutStream\fP & \fBoperator<<\fP (const \fBTiXmlString\fP &in)"
.br
.ti -1c
.RI "\fBTiXmlOutStream\fP & \fBoperator<<\fP (const char *in)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
