.TH "TiXmlParsingData" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TiXmlParsingData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStamp\fP (const char *now, TiXmlEncoding encoding)"
.br
.ti -1c
.RI "const \fBTiXmlCursor\fP & \fBCursor\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTiXmlDocument\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
