.TH "Vent" 3 "Wed Apr 20 2016" "Incendie" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVent\fP (float _power_h, float _power_v)"
.br
.ti -1c
.RI "\fBVent\fP (const \fBVent\fP &other)"
.br
.ti -1c
.RI "void \fBsetPower_h\fP (float val)"
.br
.ti -1c
.RI "void \fBsetPower_v\fP (float val)"
.br
.ti -1c
.RI "int \fBgetPower_h\fP () const "
.br
.ti -1c
.RI "int \fBgetPower_v\fP () const "
.br
.ti -1c
.RI "virtual \fBVent\fP & \fBoperator+\fP (const \fBVent\fP &other)"
.br
.ti -1c
.RI "virtual \fBVent\fP & \fBoperator\-\fP (const \fBVent\fP &other)"
.br
.ti -1c
.RI "virtual \fBVent\fP & \fBoperator*\fP (float coefficient)"
.br
.ti -1c
.RI "virtual \fBVent\fP & \fBoperator/\fP (float coefficient)"
.br
.ti -1c
.RI "virtual \fBVent\fP & \fBoperator=\fP (const \fBVent\fP &other)"
.br
.ti -1c
.RI "virtual \fBVent\fP & \fBoperator+=\fP (const \fBVent\fP &other)"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const "
.br
.ti -1c
.RI "int \fBgetSpeed\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Incendie from the source code\&.
