mocs: firescreen.h
	moc firescreen.h	-o ./mocs/moc_firescreen.cpp
	moc firewidget.h	-o ./mocs/moc_firewidget.cpp
	moc fwelcome.h 		-o ./mocs/moc_fwelcome.cpp
	moc windcircle.h	-o ./mocs/moc_windcircle.cpp
	moc windwidget.h	-o ./mocs/moc_windwidget.cpp